services:
  postgres:
    container_name: fintrack_postgres_db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=fintrack
      - POSTGRES_PASSWORD=fintrack
      - POSTGRES_DB=fintrack_db
    volumes:
      - fintrack-postgres-data:/var/lib/postgresql/data
    networks:
      - shared-net

  fintrack_app:
    container_name: fintrack
    image: fintrack:latest
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - shared-net
    ports:
      - 6002:6002
      - 6003:6003

volumes:
  fintrack-postgres-data:
    driver: local
networks:
  shared-net:
    external: true
    name: fintrack-network
